[package]
name = "ident"
version = "2.0.0"
edition = "2021"

[dependencies]
fastrand = "2.0"
thiserror = "1.0"
konst = { version = "0.3.6", features = ["cmp"] }

[dev-dependencies]
proptest = "1.2.0"
